// --- Core Book Recommendation ---

export interface BookRecommendation {
  id: string
  title: string
  author: string
  recommender: string
  friendNote?: string
  dateAdded: string // ISO 8601

  // AI generation
  aiPitch?: string
  tasteScore?: number        // 1–10, generated by Claude
  aiPitchGeneratedAt?: string
}

// --- Generic CSV Import ---

export interface CsvColumnMap {
  title: string | null
  author: string | null
  genre: string | null
  series: string | null    // series name — great signal for pattern recognition
  dateRead: string | null
  shelf: string | null     // for filtering to "read" books if present
}

export interface BookHistoryRow {
  title: string
  author: string
  genre: string | null
  series: string | null
  dateRead: string | null
  shelf: string | null
  rawRow: Record<string, string>
}

// --- Taste Profile ---

export interface TasteProfile {
  totalBooksRead: number
  topGenres: Array<{ genre: string; count: number; percentage: number }>
  topAuthors: Array<{ author: string; count: number }>
  seriesRead: Array<{ series: string; count: number }>   // series they completed/read deeply
  sampleBooks: BookHistoryRow[]                          // representative titles for AI context
  importedAt: string
  sourceName: string
}

// --- App State ---

export interface AppState {
  books: BookRecommendation[]
  tasteProfile: TasteProfile | null
  apiKey: string
}

// --- UI State ---

export type ViewName = 'library' | 'import' | 'taste-profile' | 'settings'

export type SortField = 'dateAdded' | 'title' | 'author' | 'recommender' | 'tasteScore'
export type SortDirection = 'asc' | 'desc'
